// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFL3QRC5BLt_tksfKTwmVhlKLcDcegdXo',
    appId: '1:264970202915:android:86566d02ce6719f7fee696',
    messagingSenderId: '264970202915',
    projectId: 'workapp-13b1f',
    storageBucket: 'workapp-13b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPajaSm5Pkha90e8aJN4NFwVULxutSbQ',
    appId: '1:264970202915:ios:36bbfd3acf70f15dfee696',
    messagingSenderId: '264970202915',
    projectId: 'workapp-13b1f',
    storageBucket: 'workapp-13b1f.firebasestorage.app',
    iosBundleId: 'com.example.workapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_OsDFQexKSS9meDu5vbSlstIuIjJWFhg',
    appId: '1:264970202915:web:49d0bcb609b4fc04fee696',
    messagingSenderId: '264970202915',
    projectId: 'workapp-13b1f',
    authDomain: 'workapp-13b1f.firebaseapp.com',
    storageBucket: 'workapp-13b1f.firebasestorage.app',
    measurementId: 'G-MHCT5N1M8W',
  );
}
